export const timeZoneOptions = [
  {label: '(UTC-12:00) International Date Line West', value: 'Etc/GMT+12'},
  {label: '(UTC-11:00) Coordinated Universal Time-11', value: 'Etc/GMT+11'},
  {label: '(UTC-10:00) Hawaii', value: 'Etc/GMT+10'},
  {label: '(UTC-09:00) Alaska', value: 'America/Anchorage'},
  {label: '(UTC-08:00) Baja California', value: 'America/Santa_Isabel'},
  {label: '(UTC-07:00) Pacific Time', value: 'America/Dawson'},
  {label: '(UTC-08:00) Pacific Time', value: 'America/Dawson'},
  {label: '(UTC-07:00) Arizona', value: 'America/Creston'},
  {label: '(UTC-07:00) Chihuahua, La Paz, Mazatlan', value: 'America/Chihuahua'},
  {label: '(UTC-07:00) Mountain Time', value: 'America/Boise'},
  {label: '(UTC-06:00) Central America', value: 'America/Belize'},
  {label: '(UTC-06:00) Central Time', value: 'America/Chicago'},
  {label: '(UTC-06:00) Guadalajara, Mexico City, Monterrey', value: 'America/Bahia_Banderas'},
  {label: '(UTC-06:00) Saskatchewan', value: 'America/Regina'},
  {label: '(UTC-05:00) Bogota, Lima, Quito', value: 'America/Bogota'},
  {label: '(UTC-05:00) Eastern Time', value: 'America/Detroit'},
  {label: '(UTC-05:00) Indiana (East)', value: 'America/Indiana/Marengo'},
  {label: '(UTC-04:30) Caracas', value: 'America/Caracas'},
  {label: '(UTC-04:00) Asuncion', value: 'America/Asuncion'},
  {label: '(UTC-04:00) Atlantic Time (Canada)', value: 'America/Glace_Bay'},
  {label: '(UTC-04:00) Cuiaba', value: 'America/Campo_Grande'},
  {label: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan', value: 'America/Anguilla'},
  {label: '(UTC-04:00) Santiago', value: 'America/Santiago'},
  {label: '(UTC-03:30) Newfoundland', value: 'America/St_Johns'},
  {label: '(UTC-03:00) Brasilia', value: 'America/Sao_Paulo'},
  {label: '(UTC-03:00) Buenos Aires', value: 'America/Argentina/La_Rioja'},
  {label: '(UTC-03:00) Cayenne, Fortaleza', value: 'America/Araguaina'},
  {label: '(UTC-03:00) Greenland', value: 'America/Godthab'},
  {label: '(UTC-03:00) Montevideo', value: 'America/Montevideo'},
  {label: '(UTC-03:00) Salvador', value: 'America/Bahia'},
  {label: '(UTC-02:00) Coordinated Universal Time-02', value: 'America/Noronha'},
  {label: '(UTC-02:00) Mid-Atlantic - Old', value: 'Mid_Atlantic_Old'},
  {label: '(UTC-01:00) Azores', value: 'America/Scoresbysund'},
  {label: '(UTC-01:00) Cape Verde Is.', value: 'Atlantic/Cape_Verde'},
  {label: '(UTC) Casablanca', value: 'Africa/Casablanca'},
  {label: '(UTC) Coordinated Universal Time', value: 'America/Danmarkshavn'},
  {label: '(UTC) Edinburgh, London', value: 'Europe/Isle_of_Man'},
  {label: '(UTC+01:00) Edinburgh, London', value: 'Europe/Isle_of_Man'},
  {label: '(UTC) Dublin, Lisbon', value: 'Atlantic/Canary'},
  {label: '(UTC) Monrovia, Reykjavik', value: 'Africa/Abidjan'},
  {label: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna', value: 'Arctic/Longyearbyen'},
  {label: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague', value: 'Europe/Belgrade'},
  {label: '(UTC+02:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague', value: 'Europe/Belgrade'},
  {label: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris', value: 'Africa/Ceuta'},
  {label: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb', value: 'Europe/Sarajevo'},
  {label: '(UTC+01:00) West Central Africa', value: 'Africa/Algiers'},
  {label: '(UTC+01:00) Windhoek', value: 'Africa/Windhoek'},
  {label: '(UTC+02:00) Athens, Bucharest', value: 'Asia/Nicosia'},
  {label: '(UTC+02:00) Beirut', value: 'Asia/Beirut'},
  {label: '(UTC+02:00) Cairo', value: 'Africa/Cairo'},
  {label: '(UTC+02:00) Damascus', value: 'Asia/Damascus'},
  {label: '(UTC+02:00) E. Europe', value: 'Asia/Nicosia'},
  {label: '(UTC+03:00) E. Europe', value: 'Asia/Nicosia'},
  {label: '(UTC+02:00) Harare, Pretoria', value: 'Africa/Blantyre'},
  {label: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius', value: 'Europe/Helsinki'},
  {label: '(UTC+03:00) Istanbul', value: 'Europe/Istanbul'},
  {label: '(UTC+02:00) Jerusalem', value: 'Asia/Jerusalem'},
  {label: '(UTC+02:00) Tripoli', value: 'Africa/Tripoli'},
  {label: '(UTC+03:00) Amman', value: 'Asia/Amman'},
  {label: '(UTC+03:00) Baghdad', value: 'Asia/Baghdad'},
  {label: '(UTC+02:00) Kaliningrad', value: 'Europe/Kaliningrad'},
  {label: '(UTC+03:00) Kuwait, Riyadh', value: 'Asia/Aden'},
  {label: '(UTC+03:00) Nairobi', value: 'Africa/Addis_Ababa'},
  {label: '(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk', value: 'Europe/Kirov'},
  {label: '(UTC+04:00) Samara, Ulyanovsk, Saratov', value: 'Europe/Astrakhan'},
  {label: '(UTC+03:30) Tehran', value: 'Asia/Tehran'},
  {label: '(UTC+04:00) Abu Dhabi, Muscat', value: 'Asia/Dubai'},
  {label: '(UTC+04:00) Baku', value: 'Asia/Baku'},
  {label: '(UTC+04:00) Port Louis', value: 'Indian/Mahe'},
  {label: '(UTC+04:00) Tbilisi', value: 'Asia/Tbilisi'},
  {label: '(UTC+04:00) Yerevan', value: 'Asia/Yerevan'},
  {label: '(UTC+04:30) Kabul', value: 'Asia/Kabul'},
  {label: '(UTC+05:00) Ashgabat, Tashkent', value: 'Antarctica/Mawson'},
  {label: '(UTC+05:00) Yekaterinburg', value: 'Asia/Yekaterinburg'},
  {label: '(UTC+05:00) Islamabad, Karachi', value: 'Asia/Karachi'},
  {label: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi', value: 'Asia/Kolkata'},
  {label: '(UTC+05:30) Sri Jayawardenepura', value: 'Asia/Colombo'},
  {label: '(UTC+05:45) Kathmandu', value: 'Asia/Kathmandu'},
  {label: '(UTC+06:00) Nur-Sultan (Astana)', value: 'Antarctica/Vostok'},
  {label: '(UTC+06:00) Dhaka', value: 'Asia/Dhaka'},
  {label: '(UTC+06:30) Yangon (Rangoon)', value: 'Asia/Rangoon'},
  {label: '(UTC+07:00) Bangkok, Hanoi, Jakarta', value: 'Antarctica/Davis'},
  {label: '(UTC+07:00) Novosibirsk', value: 'Asia/Novokuznetsk'},
  {label: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi', value: 'Asia/Hong_Kong'},
  {label: '(UTC+08:00) Krasnoyarsk', value: 'Asia/Krasnoyarsk'},
  {label: '(UTC+08:00) Kuala Lumpur, Singapore', value: 'Asia/Brunei'},
  {label: '(UTC+08:00) Perth', value: 'Antarctica/Casey'},
  {label: '(UTC+08:00) Taipei', value: 'Asia/Taipei'},
  {label: '(UTC+08:00) Ulaanbaatar', value: 'Asia/Choibalsan'},
  {label: '(UTC+08:00) Irkutsk', value: 'Asia/Irkutsk'},
  {label: '(UTC+09:00) Osaka, Sapporo, Tokyo', value: 'Asia/Dili'},
  {label: '(UTC+09:00) Seoul', value: 'Asia/Pyongyang'},
  {label: '(UTC+09:30) Adelaide', value: 'Australia/Adelaide'},
  {label: '(UTC+09:30) Darwin', value: 'Australia/Darwin'},
  {label: '(UTC+10:00) Brisbane', value: 'Australia/Brisbane'},
  {label: '(UTC+10:00) Canberra, Melbourne, Sydney', value: 'Australia/Melbourne'},
  {label: '(UTC+10:00) Guam, Port Moresby', value: 'Antarctica/DumontDUrville'},
  {label: '(UTC+10:00) Hobart', value: 'Australia/Currie'},
  {label: '(UTC+09:00) Yakutsk', value: 'Asia/Chita'},
  {label: '(UTC+11:00) Solomon Is., New Caledonia', value: 'Antarctica/Macquarie'},
  {label: '(UTC+11:00) Vladivostok', value: 'Asia/Sakhalin'},
  {label: '(UTC+12:00) Auckland, Wellington', value: 'Antarctica/McMurdo'},
  {label: '(UTC+12:00) Coordinated Universal Time+12', value: 'Etc/GMT-12'},
  {label: '(UTC+12:00) Fiji', value: 'Pacific/Fiji'},
  {label: '(UTC+12:00) Magadan', value: 'Asia/Anadyr'},
  {label: '(UTC+12:00) Petropavlovsk-Kamchatsky - Old', value: 'Asia/Kamchatka'},
  {label: '(UTC+13:00) Nuku\'alofa', value: 'Etc/GMT-13'},
  {label: '(UTC+13:00) Samoa', value: 'Pacific/Apia'},
]
