export const timeZoneOptions = [
    {label: '(UTC-12:00) International Date Line West', value: 'Dateline Standard Time'},
    {label: '(UTC-11:00) Coordinated Universal Time-11', value: 'UTC-11'},
    {label: '(UTC-10:00) Hawaii', value: 'Hawaiian Standard Time'},
    {label: '(UTC-09:00) Alaska', value: 'Alaskan Standard Time'},
    {label: '(UTC-08:00) Baja California', value: 'Pacific Standard Time (Mexico)'},
    {label: '(UTC-07:00) Pacific Time', value: 'Pacific Daylight Time'},
    {label: '(UTC-08:00) Pacific Time', value: 'Pacific Standard Time'},
    {label: '(UTC-07:00) Arizona', value: 'US Mountain Standard Time'},
    {label: '(UTC-07:00) Chihuahua, La Paz, Mazatlan', value: 'Mountain Standard Time (Mexico)'},
    {label: '(UTC-07:00) Mountain Time', value: 'Mountain Standard Time'},
    {label: '(UTC-06:00) Central America', value: 'Central America Standard Time'},
    {label: '(UTC-06:00) Central Time', value: 'Central Standard Time'},
    {label: '(UTC-06:00) Guadalajara, Mexico City, Monterrey', value: 'Central Standard Time (Mexico)'},
    {label: '(UTC-06:00) Saskatchewan', value: 'Canada Central Standard Time'},
    {label: '(UTC-05:00) Bogota, Lima, Quito', value: 'SA Pacific Standard Time'},
    {label: '(UTC-05:00) Eastern Time', value: 'Eastern Standard Time'},
    {label: '(UTC-05:00) Indiana (East)', value: 'US Eastern Standard Time'},
    {label: '(UTC-04:30) Caracas', value: 'Venezuela Standard Time'},
    {label: '(UTC-04:00) Asuncion', value: 'Paraguay Standard Time'},
    {label: '(UTC-04:00) Atlantic Time (Canada)', value: 'Atlantic Standard Time'},
    {label: '(UTC-04:00) Cuiaba', value: 'Central Brazilian Standard Time'},
    {label: '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan', value: 'SA Western Standard Time'},
    {label: '(UTC-04:00) Santiago', value: 'Pacific SA Standard Time'},
    {label: '(UTC-03:30) Newfoundland', value: 'Newfoundland Standard Time'},
    {label: '(UTC-03:00) Brasilia', value: 'E. South America Standard Time'},
    {label: '(UTC-03:00) Buenos Aires', value: 'Argentina Standard Time'},
    {label: '(UTC-03:00) Cayenne, Fortaleza', value: 'SA Eastern Standard Time'},
    {label: '(UTC-03:00) Greenland', value: 'Greenland Standard Time'},
    {label: '(UTC-03:00) Montevideo', value: 'Montevideo Standard Time'},
    {label: '(UTC-03:00) Salvador', value: 'Bahia Standard Time'},
    {label: '(UTC-02:00) Coordinated Universal Time-02', value: 'UTC-02'},
    {label: '(UTC-02:00) Mid-Atlantic - Old', value: 'Mid-Atlantic Standard Time'},
    {label: '(UTC-01:00) Azores', value: 'Azores Standard Time'},
    {label: '(UTC-01:00) Cape Verde Is.', value: 'Cape Verde Standard Time'},
    {label: '(UTC) Casablanca', value: 'Morocco Standard Time'},
    {label: '(UTC) Coordinated Universal Time', value: 'UTC'},
    {label: '(UTC) Edinburgh, London', value: 'GMT Standard Time'},
    {label: '(UTC+01:00) Edinburgh, London', value: 'British Summer Time'},
    {label: '(UTC) Dublin, Lisbon', value: 'GDT Standard Time'},
    {label: '(UTC) Monrovia, Reykjavik', value: 'Greenwich Standard Time'},
    {label: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna', value: 'W. Europe Standard Time'},
    {label: '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague', value: 'Central Europe Standard Time'},
    {label: '(UTC+02:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague', value: 'Central European Summer Time'},
    {label: '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris', value: 'Romance Standard Time'},
    {label: '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb', value: 'Central European Standard Time'},
    {label: '(UTC+01:00) West Central Africa', value: 'W. Central Africa Standard Time'},
    {label: '(UTC+01:00) Windhoek', value: 'Namibia Standard Time'},
    {label: '(UTC+02:00) Athens, Bucharest', value: 'GTB Standard Time'},
    {label: '(UTC+02:00) Beirut', value: 'Middle East Standard Time'},
    {label: '(UTC+02:00) Cairo', value: 'Egypt Standard Time'},
    {label: '(UTC+02:00) Damascus', value: 'Syria Standard Time'},
    {label: '(UTC+02:00) E. Europe', value: 'E. Europe Standard Time'},
    {label: '(UTC+03:00) E. Europe', value: 'E. Europe Summer Time'},
    {label: '(UTC+02:00) Harare, Pretoria', value: 'South Africa Standard Time'},
    {label: '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius', value: 'FLE Standard Time'},
    {label: '(UTC+03:00) Istanbul', value: 'Turkey Standard Time'},
    {label: '(UTC+02:00) Jerusalem', value: 'Israel Standard Time'},
    {label: '(UTC+02:00) Tripoli', value: 'Libya Standard Time'},
    {label: '(UTC+03:00) Amman', value: 'Jordan Standard Time'},
    {label: '(UTC+03:00) Baghdad', value: 'Arabic Standard Time'},
    {label: '(UTC+02:00) Kaliningrad', value: 'Kaliningrad Standard Time'},
    {label: '(UTC+03:00) Kuwait, Riyadh', value: 'Arab Standard Time'},
    {label: '(UTC+03:00) Nairobi', value: 'E. Africa Standard Time'},
    {label: '(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk', value: 'Moscow Standard Time'},
    {label: '(UTC+04:00) Samara, Ulyanovsk, Saratov', value: 'Samara Time'},
    {label: '(UTC+03:30) Tehran', value: 'Iran Standard Time'},
    {label: '(UTC+04:00) Abu Dhabi, Muscat', value: 'Arabian Standard Time'},
    {label: '(UTC+04:00) Baku', value: 'Azerbaijan Standard Time'},
    {label: '(UTC+04:00) Port Louis', value: 'Mauritius Standard Time'},
    {label: '(UTC+04:00) Tbilisi', value: 'Georgian Standard Time'},
    {label: '(UTC+04:00) Yerevan', value: 'Caucasus Standard Time'},
    {label: '(UTC+04:30) Kabul', value: 'Afghanistan Standard Time'},
    {label: '(UTC+05:00) Ashgabat, Tashkent', value: 'West Asia Standard Time'},
    {label: '(UTC+05:00) Yekaterinburg', value: 'Yekaterinburg Time'},
    {label: '(UTC+05:00) Islamabad, Karachi', value: 'Pakistan Standard Time'},
    {label: '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi', value: 'India Standard Time'},
    {label: '(UTC+05:30) Sri Jayawardenepura', value: 'Sri Lanka Standard Time'},
    {label: '(UTC+05:45) Kathmandu', value: 'Nepal Standard Time'},
    {label: '(UTC+06:00) Nur-Sultan (Astana)', value: 'Central Asia Standard Time'},
    {label: '(UTC+06:00) Dhaka', value: 'Bangladesh Standard Time'},
    {label: '(UTC+06:30) Yangon (Rangoon)', value: 'Myanmar Standard Time'},
    {label: '(UTC+07:00) Bangkok, Hanoi, Jakarta', value: 'SE Asia Standard Time'},
    {label: '(UTC+07:00) Novosibirsk', value: 'N. Central Asia Standard Time'},
    {label: '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi', value: 'China Standard Time'},
    {label: '(UTC+08:00) Krasnoyarsk', value: 'North Asia Standard Time'},
    {label: '(UTC+08:00) Kuala Lumpur, Singapore', value: 'Singapore Standard Time'},
    {label: '(UTC+08:00) Perth', value: 'W. Australia Standard Time'},
    {label: '(UTC+08:00) Taipei', value: 'Taipei Standard Time'},
    {label: '(UTC+08:00) Ulaanbaatar', value: 'Ulaanbaatar Standard Time'},
    {label: '(UTC+08:00) Irkutsk', value: 'North Asia East Standard Time'},
    {label: '(UTC+09:00) Osaka, Sapporo, Tokyo', value: 'Japan Standard Time'},
    {label: '(UTC+09:00) Seoul', value: 'Korea Standard Time'},
    {label: '(UTC+09:30) Adelaide', value: 'Cen. Australia Standard Time'},
    {label: '(UTC+09:30) Darwin', value: 'AUS Central Standard Time'},
    {label: '(UTC+10:00) Brisbane', value: 'E. Australia Standard Time'},
    {label: '(UTC+10:00) Canberra, Melbourne, Sydney', value: 'AUS Eastern Standard Time'},
    {label: '(UTC+10:00) Guam, Port Moresby', value: 'West Pacific Standard Time'},
    {label: '(UTC+10:00) Hobart', value: 'Tasmania Standard Time'},
    {label: '(UTC+09:00) Yakutsk', value: 'Yakutsk Standard Time'},
    {label: '(UTC+11:00) Solomon Is., New Caledonia', value: 'Central Pacific Standard Time'},
    {label: '(UTC+11:00) Vladivostok', value: 'Vladivostok Standard Time'},
    {label: '(UTC+12:00) Auckland, Wellington', value: 'New Zealand Standard Time'},
    {label: '(UTC+12:00) Coordinated Universal Time+12', value: 'UTC+12'},
    {label: '(UTC+12:00) Fiji', value: 'Fiji Standard Time'},
    {label: '(UTC+12:00) Magadan', value: 'Magadan Standard Time'},
    {label: '(UTC+12:00) Petropavlovsk-Kamchatsky - Old', value: 'Kamchatka Standard Time'},
    {label: "(UTC+13:00) Nuku'alofa", value: 'Tonga Standard Time'},
    {label: '(UTC+13:00) Samoa', value: 'Samoa Standard Time'},
]
